Repository Amething/amething-server, pull requests merged in 2022-06, with the labels that each got.

#12 Feature/user profile
  src/main/java/com/server/amething/domain/question/Question.java
  src/main/java/com/server/amething/domain/user/controller/UserController.java
  src/main/java/com/server/amething/domain/user/dto/ProfileDto.java
  src/main/java/com/server/amething/domain/user/repository/UserRepository.java
  src/main/java/com/server/amething/domain/user/repository/UserRepositoryCustom.java
  src/main/java/com/server/amething/domain/user/repository/UserRepositoryImpl.java
  src/main/java/com/server/amething/domain/user/service/UserService.java
  src/main/java/com/server/amething/domain/user/service/UserServiceImpl.java
  src/main/java/com/server/amething/global/config/querydsl/QuerydslConfig.java
  src/test/java/com/server/amething/domain/user/controller/UserControllerTest.java
  src/test/java/com/server/amething/domain/user/service/UserServiceTest.java
Labels: Build Success

#13 JWT 인증인가 구현 및 login 구현
  build.gradle
  src/main/java/com/server/amething/domain/auth/controller/OauthController.java
  src/main/java/com/server/amething/domain/user/User.java
  src/main/java/com/server/amething/domain/user/controller/UserController.java
  src/main/java/com/server/amething/domain/user/enum_type/Role.java
  src/main/java/com/server/amething/domain/user/repository/UserRepository.java
  src/main/java/com/server/amething/domain/user/repository/UserRepositoryCustom.java
  src/main/java/com/server/amething/domain/user/repository/UserRepositoryImpl.java
  src/main/java/com/server/amething/domain/user/service/UserService.java
  src/main/java/com/server/amething/domain/user/service/UserServiceImpl.java
  src/main/java/com/server/amething/global/jwt/JwtFilter.java
  src/main/java/com/server/amething/global/jwt/JwtTokenProvider.java
  src/main/java/com/server/amething/global/jwt/config/CustomUserDetails.java
  src/main/java/com/server/amething/global/jwt/config/JwtFilterConfig.java
  src/main/java/com/server/amething/global/jwt/exception/JwtAccessDeniedHandler.java
  src/main/java/com/server/amething/global/jwt/exception/JwtAuthenticationEntryPoint.java
  src/main/java/com/server/amething/global/util/UserUtil.java
  src/test/java/com/server/amething/domain/user/controller/UserControllerTest.java
  src/test/java/com/server/amething/domain/user/service/UserServiceTest.java
  src/test/java/com/server/amething/util/UserUtilTest.java
Labels: documentation, Build Success, ok, Code Review

#15 Feature/user profile fix
  src/main/java/com/server/amething/domain/user/controller/UserController.java
  src/main/java/com/server/amething/domain/user/dto/ProfileDto.java
  src/main/java/com/server/amething/domain/user/repository/UserRepositoryCustom.java
  src/main/java/com/server/amething/domain/user/repository/UserRepositoryImpl.java
  src/main/java/com/server/amething/domain/user/service/UserService.java
  src/main/java/com/server/amething/domain/user/service/UserServiceImpl.java
  src/test/java/com/server/amething/domain/user/controller/UserControllerTest.java
  src/test/java/com/server/amething/domain/user/service/UserServiceTest.java
Labels: Build Success

#17 RefreshToken을 이용한 AccessToken 재발급
  src/main/java/com/server/amething/domain/token/controller/TokenController.java
  src/main/java/com/server/amething/domain/token/service/TokenService.java
  src/main/java/com/server/amething/domain/token/service/TokenServiceImpl.java
  src/main/java/com/server/amething/domain/user/User.java
  src/main/java/com/server/amething/global/config/security/WebSecurityConfig.java
  src/main/java/com/server/amething/global/jwt/JwtTokenProvider.java
  src/main/java/com/server/amething/global/jwt/config/CustomUserDetails.java
  src/main/java/com/server/amething/global/jwt/exception/ExceptionHandlerFilter.java
  src/main/java/com/server/amething/global/jwt/exception/ExceptionHandlerFilterConfig.java
Labels: Build Success, ok, Code Review

#21 QuestionRepository 추가
  src/main/java/com/server/amething/domain/question/repository/QuestionRepository.java
Labels: ok

#23 질문 엔티티의 description을 title로 네이밍 변경
  src/main/java/com/server/amething/domain/question/Question.java
Labels: Build Success, ok

#25 bio 변경 로직 추가
  src/main/java/com/server/amething/domain/user/User.java
  src/main/java/com/server/amething/domain/user/controller/UserController.java
  src/main/java/com/server/amething/domain/user/dto/ChangeBioDto.java
  src/main/java/com/server/amething/domain/user/service/UserService.java
  src/main/java/com/server/amething/domain/user/service/UserServiceImpl.java
  src/test/java/com/server/amething/domain/user/service/UserServiceTest.java
Labels: Build Success, ok, Code Review

#27 테스트와 개발편의성을 위해 PostConstruct를 이용해 유저를 가입시켜놓는 util 클래스를 개발
  src/main/java/com/server/amething/global/util/GenerateMemberUtil.java
Labels: Build Success, ok

#28 hotfix @BeforeEach로 생성하는 user의 oauthId값 변경
  src/test/java/com/server/amething/domain/question/service/QuestionServiceTest.java
  src/test/java/com/server/amething/domain/user/service/UserServiceTest.java
Labels: Build Success, ok

#29 Feature/testcode fix
  src/test/java/com/server/amething/domain/question/service/QuestionServiceTest.java
  src/test/java/com/server/amething/domain/user/controller/UserControllerTest.java
  src/test/java/com/server/amething/domain/user/service/UserServiceTest.java
Labels: Build Success, Code Review
